spring:
  application:
    name: PetLogs

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pettrainer?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:ssafy}
    password: ${DB_PASSWORD:ssafy}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.pettrainer.pro

server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
